repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write]
        files: '\.(js|jsx|ts|tsx|vue|css|scss|less|html|json|yaml|yml|md)$'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.34.0
    hooks:
      - id: eslint
        args: [--fix, --cache]
        files: '\.(js|jsx|ts|tsx|vue)$'
        types: [file]
  - repo: local
    hooks:
      - id: check-commit-msg
        name: "Valida mensagem de commit"
        language: system
        entry: |
          bash -c 'if ! grep -qE "^(feat|fix|doc|style|refactor|test|chore)[[:space:]]+\([a-zA-Z0-9-]+\):[[:space:]].+" "$1"; then echo -e "\nErro: A mensagem de commit não segue o padrão.\n\nFormato esperado: {tipo} ({chave_jira}): {descrição_curta}"; exit 1; fi'
        args: [".git/COMMIT_EDITMSG"]
        stages: [commit-msg]
